"""Direct market-learning research primitives for Phase 8A."""

from .contracts import (
    BASE_FEATURE_DEFINITION_VERSION,
    EVIDENCE_LABEL,
    EXPERIMENT_ID,
    HORIZONS_MINUTES,
    MARKET_FEATURE_SET_VERSION,
    MARKET_HISTORY_END_EXCLUSIVE,
    MARKET_HISTORY_START,
    PROTOCOL_VERSION,
    SLIPPAGE_PIPS,
    MarketObservation,
    MarketOutcomeLabel,
    MarketOutcomeResult,
)
from .evidence import load_feature_evidence_index
from .execution_status import (
    FEATURE_WORKFLOW_NAME,
    FEATURE_WORKFLOW_PATH,
    OUTCOME_WORKFLOW_NAME,
    OUTCOME_WORKFLOW_PATH,
    STATUS_VERSION,
    build_execution_status,
    compile_execution_status,
    load_workflow_run,
    validate_workflow_run,
)
from .features import (
    LoadedMarketFeatureSource,
    build_market_feature_frame,
    load_market_feature_source,
    materialize_market_feature_pair,
    run_market_feature_generation,
    run_market_feature_pair_generation,
    validate_market_feature_range,
    write_market_feature_artifacts,
)
from .labels import label_market_outcome, label_market_outcomes
from .materialize import (
    LoadedFeatureCell,
    load_verified_feature_cell,
    load_verified_minute_quotes,
    materialize_market_outcome_cell,
    materialize_market_outcome_pair,
    run_market_outcome_materialization,
    run_market_outcome_pair_materialization,
)
from .operator import (
    FEATURE_WORKFLOW_FILE as OPERATOR_FEATURE_WORKFLOW_FILE,
    OUTCOME_WORKFLOW_FILE as OPERATOR_OUTCOME_WORKFLOW_FILE,
    PRESERVATION_WORKFLOW_FILE as OPERATOR_PRESERVATION_WORKFLOW_FILE,
    REPOSITORY as OPERATOR_REPOSITORY,
    feature_dispatch_command,
    feature_run_endpoint,
    feature_runs_endpoint,
    outcome_dispatch_command,
    outcome_runs_endpoint,
    preservation_dispatch_command,
    preservation_runs_endpoint,
    shell_join,
    validate_feature_run_for_outcomes,
    validate_no_existing_manual_runs,
    validate_operator_checkout,
)
from .outcome_evidence import (
    compile_outcome_evidence,
    load_outcome_evidence_index,
    write_outcome_evidence,
)
from .readiness import (
    READINESS_VERSION,
    build_training_readiness,
    compile_training_readiness,
    load_training_readiness,
    write_training_readiness,
)
from .source_preservation import (
    PRESERVATION_TAG,
    PRESERVATION_TITLE,
    PRESERVATION_VERSION,
    build_preservation_manifest,
    release_asset_name,
    validate_release_metadata,
    write_preservation_manifest,
)
from .source_preflight import (
    PHASE2_SOURCE_HEAD_SHA,
    PHASE2_SOURCE_RUN_ID,
    SOURCE_ARTIFACTS,
    SourceArtifactSpec,
    compile_source_preflight,
    load_metadata_directory,
    validate_source_artifact_metadata,
    write_source_preflight,
)
from .outcomes import (
    MARKET_OUTCOME_SET_VERSION,
    OUTCOME_COLUMNS,
    OUTCOME_FEATURE_IDENTITY_COLUMNS,
    MarketOutcomeGridBuild,
    build_market_outcome_grid,
    build_market_outcome_grid_from_identity,
    write_market_outcome_artifacts,
)

__all__ = [
    "BASE_FEATURE_DEFINITION_VERSION",
    "EVIDENCE_LABEL",
    "EXPERIMENT_ID",
    "HORIZONS_MINUTES",
    "FEATURE_WORKFLOW_NAME",
    "FEATURE_WORKFLOW_PATH",
    "MARKET_FEATURE_SET_VERSION",
    "MARKET_HISTORY_END_EXCLUSIVE",
    "MARKET_HISTORY_START",
    "PROTOCOL_VERSION",
    "SLIPPAGE_PIPS",
    "LoadedFeatureCell",
    "LoadedMarketFeatureSource",
    "MarketObservation",
    "MarketOutcomeLabel",
    "MarketOutcomeResult",
    "MarketOutcomeGridBuild",
    "MARKET_OUTCOME_SET_VERSION",
    "OUTCOME_COLUMNS",
    "OUTCOME_FEATURE_IDENTITY_COLUMNS",
    "OUTCOME_WORKFLOW_NAME",
    "OUTCOME_WORKFLOW_PATH",
    "OPERATOR_FEATURE_WORKFLOW_FILE",
    "OPERATOR_OUTCOME_WORKFLOW_FILE",
    "OPERATOR_PRESERVATION_WORKFLOW_FILE",
    "OPERATOR_REPOSITORY",
    "PRESERVATION_TAG",
    "PRESERVATION_TITLE",
    "PRESERVATION_VERSION",
    "PHASE2_SOURCE_HEAD_SHA",
    "PHASE2_SOURCE_RUN_ID",
    "READINESS_VERSION",
    "SOURCE_ARTIFACTS",
    "SourceArtifactSpec",
    "STATUS_VERSION",
    "build_execution_status",
    "build_market_feature_frame",
    "build_preservation_manifest",
    "build_market_outcome_grid",
    "build_market_outcome_grid_from_identity",
    "build_training_readiness",
    "compile_execution_status",
    "feature_dispatch_command",
    "feature_run_endpoint",
    "feature_runs_endpoint",
    "compile_outcome_evidence",
    "compile_source_preflight",
    "compile_training_readiness",
    "label_market_outcome",
    "load_feature_evidence_index",
    "load_market_feature_source",
    "materialize_market_feature_pair",
    "load_metadata_directory",
    "load_training_readiness",
    "load_workflow_run",
    "validate_workflow_run",
    "load_outcome_evidence_index",
    "load_verified_feature_cell",
    "load_verified_minute_quotes",
    "materialize_market_outcome_cell",
    "materialize_market_outcome_pair",
    "outcome_dispatch_command",
    "outcome_runs_endpoint",
    "preservation_dispatch_command",
    "preservation_runs_endpoint",
    "run_market_feature_generation",
    "run_market_feature_pair_generation",
    "run_market_outcome_materialization",
    "release_asset_name",
    "run_market_outcome_pair_materialization",
    "shell_join",
    "validate_feature_run_for_outcomes",
    "validate_market_feature_range",
    "validate_no_existing_manual_runs",
    "validate_operator_checkout",
    "validate_release_metadata",
    "validate_source_artifact_metadata",
    "write_market_feature_artifacts",
    "write_market_outcome_artifacts",
    "write_outcome_evidence",
    "write_preservation_manifest",
    "write_source_preflight",
    "write_training_readiness",
    "label_market_outcomes",
]
