from .challenger_round1 import (
    EXP013_STAGE_A_CELL_PROTOCOL,
    EXP013_STAGE_A_GATE_PROTOCOL,
    evaluate_exp013_stage_a_cell_pair,
    run_exp013_stage_a_cell,
)
from .challengers import (
    EXP013_ID,
    OPENING_RANGE_MOMENTUM_SIGNAL_CONTRACT,
    OPENING_RANGE_MOMENTUM_VERSION,
    build_opening_range_momentum_challengers,
)
from .contracts import (
    PHASE8A_EXPERIMENT_ID,
    CandidateRejection,
    CandidateRejectionCode,
    ChampionSet,
    PortfolioCandidate,
    PortfolioExposure,
    PortfolioRouteResult,
    StrategyLifecycle,
    StrategyRecord,
    StrategyVersion,
)
from .evidence import (
    JOINT_EVIDENCE_ARTIFACT_PROTOCOL,
    JOINT_EVIDENCE_PROTOCOL,
    build_joint_evidence_envelope,
    resolve_historical_strategy_records,
    write_joint_evidence_artifacts,
)
from .historical_inventory import build_phase4_baseline_inventory
from .joint_research import (
    JOINT_PORTFOLIO_PROTOCOL,
    Phase8AJointPortfolioPlan,
    run_phase8a_joint_portfolio,
)
from .registry import freeze_shadow_champion_set, transition_strategy
from .research_batch import (
    PHASE8A_BATCH_ARTIFACT_PROTOCOL,
    PHASE8A_BATCH_PROTOCOL,
    Phase8ABatchPlan,
    run_phase8a_retrospective_batch,
    select_historical_inventory,
    write_phase8a_batch_artifacts,
)
from .research_data import (
    PHASE8A_RETROSPECTIVE_END_EXCLUSIVE,
    PHASE8A_RETROSPECTIVE_LABEL,
    PHASE8A_RETROSPECTIVE_START,
    LoadedRetrospectiveBars,
    RetrospectiveRange,
    load_phase8a_retrospective_bars,
)
from .research_runner import (
    Phase8ARetrospectivePlan,
    build_strategy_config,
    generate_strategy_candidates,
    run_phase8a_retrospective_strategy,
    summarize_daily_returns,
)
from .selection import (
    NO_PORTFOLIO_SELECTED,
    PORTFOLIO_SELECTION_PASS,
    PortfolioGateResult,
    PortfolioSelectionRecord,
    SelectionPool,
    SelectionScenarioMetrics,
    annualized_compounded_return,
    enumerate_portfolio_sets,
    evaluate_selection_gates,
    freeze_selection_pool,
    rank_passing_portfolios,
)
from .router import (
    partition_direction_conflicts,
    route_shadow_candidates,
    summarize_candidate_exposure,
)

__all__ = [
    "EXP013_ID",
    "EXP013_STAGE_A_CELL_PROTOCOL",
    "EXP013_STAGE_A_GATE_PROTOCOL",
    "OPENING_RANGE_MOMENTUM_SIGNAL_CONTRACT",
    "OPENING_RANGE_MOMENTUM_VERSION",
    "PHASE8A_BATCH_ARTIFACT_PROTOCOL",
    "PHASE8A_BATCH_PROTOCOL",
    "PHASE8A_EXPERIMENT_ID",
    "PHASE8A_RETROSPECTIVE_END_EXCLUSIVE",
    "PHASE8A_RETROSPECTIVE_LABEL",
    "PHASE8A_RETROSPECTIVE_START",
    "CandidateRejection",
    "CandidateRejectionCode",
    "ChampionSet",
    "JOINT_EVIDENCE_ARTIFACT_PROTOCOL",
    "JOINT_EVIDENCE_PROTOCOL",
    "JOINT_PORTFOLIO_PROTOCOL",
    "LoadedRetrospectiveBars",
    "NO_PORTFOLIO_SELECTED",
    "PORTFOLIO_SELECTION_PASS",
    "PortfolioCandidate",
    "PortfolioGateResult",
    "PortfolioSelectionRecord",
    "PortfolioExposure",
    "PortfolioRouteResult",
    "Phase8ABatchPlan",
    "Phase8AJointPortfolioPlan",
    "Phase8ARetrospectivePlan",
    "RetrospectiveRange",
    "SelectionPool",
    "SelectionScenarioMetrics",
    "StrategyLifecycle",
    "StrategyRecord",
    "StrategyVersion",
    "annualized_compounded_return",
    "build_joint_evidence_envelope",
    "build_opening_range_momentum_challengers",
    "build_phase4_baseline_inventory",
    "build_strategy_config",
    "generate_strategy_candidates",
    "evaluate_exp013_stage_a_cell_pair",
    "enumerate_portfolio_sets",
    "evaluate_selection_gates",
    "freeze_selection_pool",
    "freeze_shadow_champion_set",
    "load_phase8a_retrospective_bars",
    "partition_direction_conflicts",
    "resolve_historical_strategy_records",
    "rank_passing_portfolios",
    "route_shadow_candidates",
    "run_exp013_stage_a_cell",
    "run_phase8a_joint_portfolio",
    "run_phase8a_retrospective_batch",
    "run_phase8a_retrospective_strategy",
    "select_historical_inventory",
    "summarize_candidate_exposure",
    "summarize_daily_returns",
    "write_joint_evidence_artifacts",
    "write_phase8a_batch_artifacts",
    "transition_strategy",
]
